version: '3.8'
services:
  # mongodb: # single node
  #   image: mongo:6.0
  #   container_name: database-mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   restart: always

  mongodb1:
    image: mongo:6.0
    container_name: mongodb1
    command: mongod --replSet mongodbCluster1 --port 27017 --bind_ip 0.0.0.0 --bind_ip_all --auth --keyFile /data/keyfile/mongo-keyfile
    ports:
      - "27027:27017"
    volumes:
      - ./keyfile/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
      - mongodb1-data:/data/db
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongol
      MONGO_INITDB_ROOT_PASSWORD: mongol_password
    restart: always

  mongodb2:
    image: mongo:6.0
    container_name: mongodb2
    command: mongod --replSet mongodbCluster1 --port 27017 --bind_ip 0.0.0.0 --bind_ip_all --auth --keyFile /data/keyfile/mongo-keyfile
    ports:
      - "27028:27017"
    volumes:
      - ./keyfile/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
      - mongodb2-data:/data/db
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongol
      MONGO_INITDB_ROOT_PASSWORD: mongol_password
    depends_on:
      - mongodb1
    restart: always

  mongodb3:
    image: mongo:6.0
    container_name: mongodb3
    command: mongod --replSet mongodbCluster1 --port 27017 --bind_ip 0.0.0.0 --bind_ip_all --auth --keyFile /data/keyfile/mongo-keyfile
    ports:
      - "27029:27017"
    volumes:
      - ./keyfile/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
      - mongodb3-data:/data/db
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongol
      MONGO_INITDB_ROOT_PASSWORD: mongol_password
    depends_on:
      - mongodb1
    restart: always

  # MongoDB setup script to initialize the replica set
  mongo_setup:
    image: mongo:6.0
    container_name: mongo_setup
    restart: on-failure
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongol
      MONGO_INITDB_ROOT_PASSWORD: mongol_password
    volumes:
      - ./keyfile/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
      - ./scripts:/scripts
    entrypoint: ["bash", "/scripts/setup.sh"]

volumes:
  mongodb-data:
  mongodb1-data:
  mongodb2-data:
  mongodb3-data:

networks:
  mongo_network:
    driver: bridge
