version: '3.8'
services:
  mysql:
    image: mysql:9
    container_name: database-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Optional, jika ingin menjalankan script saat container mulai

volumes:
  mysql_data:
    driver: local
